# Generated by Django 4.0.7 on 2022-08-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220812_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='url_user',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
