# Generated by Django 4.0.7 on 2022-08-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_about_user_profile_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
    ]
