# Generated by Django 4.0.6 on 2022-07-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_basemodel_status_type_delete_product_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='type_old',
        ),
    ]
