# Generated by Django 4.0.6 on 2022-07-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_issue_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(related_name='issues', to='webapp.type', verbose_name='Тип'),
        ),
    ]
