# Generated by Django 4.0.7 on 2022-08-12 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(default=1, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
