# Generated by Django 4.0.6 on 2022-07-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type_old',
        ),
    ]
